/**
  *****************************************************************************
  * @title   main.c
  * @author  Mark Rusciano
  * @date    13 Dec 2014
  * @brief   LED Toggled by Button
  *******************************************************************************
  */
////// The above comment is automatically generated by CoIDE ///////////////////

#include "stm32f4xx.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_rcc.h"

GPIO_InitTypeDef GPIO_InitStruct;

static void pin_setup(void)
{
	//LED Setup
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);

	GPIO_InitStruct.GPIO_Pin = GPIO_Pin_5;
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStruct.GPIO_OType = GPIO_OType_PP; //push pull vs open drain
	GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_DOWN; //pull down

	GPIO_Init(GPIOA, &GPIO_InitStruct);
	GPIO_ResetBits(GPIOA, GPIO_Pin_5);

	//Button Setup
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOC, ENABLE);

	GPIO_InitStruct.GPIO_Pin = GPIO_Pin_13;
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_IN;
	GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStruct.GPIO_OType = GPIO_OType_PP; //push pull vs open drain
	GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_DOWN; //pull down

	GPIO_Init(GPIOC, &GPIO_InitStruct);
	GPIO_ResetBits(GPIOC, GPIO_Pin_13);
}

int main(void)
{
	pin_setup();

	int led_state;

	while(1)
	{
		int pressed = GPIO_ReadInputDataBit(GPIOC, GPIO_Pin_13);
		if(!pressed)
		{
			led_state = !led_state;
		}
		GPIO_WriteBit(GPIOA, GPIO_Pin_5, (BitAction) led_state);

//		int pressed = GPIO_ReadInputDataBit(GPIOC, GPIO_Pin_13);
//		GPIO_WriteBit(GPIOA, GPIO_Pin_5, (BitAction) !pressed);
	}
}
